apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-k8s-chat-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-k8s-chat-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-k8s-chat-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: ai-k8s-chat-sa
  namespace: default
roleRef:
  kind: Role
  name: ai-k8s-chat-role
  apiGroup: rbac.authorization.k8s.io
